// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGoogleLogin(arg1) {
  return window['go']['main']['App']['CancelGoogleLogin'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function DeleteGoogleAccount(arg1) {
  return window['go']['main']['App']['DeleteGoogleAccount'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetGatewayStatus() {
  return window['go']['main']['App']['GetGatewayStatus']();
}

export function GetGoogleLoginStatus(arg1) {
  return window['go']['main']['App']['GetGoogleLoginStatus'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportGLabsBackup(arg1) {
  return window['go']['main']['App']['ImportGLabsBackup'](arg1);
}

export function ListGoogleAccounts() {
  return window['go']['main']['App']['ListGoogleAccounts']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenGoogleAccountBrowser(arg1) {
  return window['go']['main']['App']['OpenGoogleAccountBrowser'](arg1);
}

export function RefreshAllGoogleAccounts() {
  return window['go']['main']['App']['RefreshAllGoogleAccounts']();
}

export function RefreshGoogleAccount(arg1) {
  return window['go']['main']['App']['RefreshGoogleAccount'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SaveGoogleAccountProxy(arg1, arg2) {
  return window['go']['main']['App']['SaveGoogleAccountProxy'](arg1, arg2);
}

export function UpdateGoogleAccountFeatures(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGoogleAccountFeatures'](arg1, arg2, arg3);
}

export function BulkUpdateGoogleAccountFeatures(arg1, arg2) {
  return window['go']['main']['App']['BulkUpdateGoogleAccountFeatures'](arg1, arg2);
}


export function StartGateway(arg1) {
  return window['go']['main']['App']['StartGateway'](arg1);
}

export function StartGoogleLogin(arg1) {
  return window['go']['main']['App']['StartGoogleLogin'](arg1);
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function TestGoogleAccount(arg1) {
  return window['go']['main']['App']['TestGoogleAccount'](arg1);
}

export function ToggleGateway() {
  return window['go']['main']['App']['ToggleGateway']();
}

export function ToggleGoogleAccount(arg1, arg2) {
  return window['go']['main']['App']['ToggleGoogleAccount'](arg1, arg2);
}

export function UpdateGatewayPort(arg1) {
  return window['go']['main']['App']['UpdateGatewayPort'](arg1);
}
