// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelGoogleLogin(arg1:string):Promise<void>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function DeleteGoogleAccount(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<models.UserResponse>;

export function GetGatewayStatus():Promise<models.GatewayStatus>;

export function GetGoogleLoginStatus(arg1:string):Promise<models.LoginSessionStatus>;

export function GetSettings():Promise<models.AppSettings>;

export function ImportGLabsBackup(arg1:string):Promise<number>;

export function ListGoogleAccounts():Promise<Array<models.GoogleAccountResponse>>;

export function Login(arg1:string,arg2:string):Promise<models.UserResponse>;

export function Logout():Promise<boolean>;

export function OpenGoogleAccountBrowser(arg1:string):Promise<void>;

export function RefreshAllGoogleAccounts():Promise<Array<models.GoogleAccountResponse>>;

export function RefreshGoogleAccount(arg1:string):Promise<models.GoogleAccountResponse>;

export function Register(arg1:string,arg2:string):Promise<models.UserResponse>;

export function SaveGoogleAccountProxy(arg1:string,arg2:string):Promise<void>;

export function StartGateway(arg1:number):Promise<models.GatewayStatus>;

export function StartGoogleLogin(arg1:string):Promise<models.LoginSessionStatus>;

export function StopGateway():Promise<models.GatewayStatus>;

export function TestGoogleAccount(arg1:string):Promise<models.AccountTestResult>;

export function ToggleGateway():Promise<models.GatewayStatus>;

export function ToggleGoogleAccount(arg1:string,arg2:boolean):Promise<models.GoogleAccountResponse>;

export function UpdateGatewayPort(arg1:number):Promise<models.GatewayStatus>;

export function UpdateGoogleAccountFeatures(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function BulkUpdateGoogleAccountFeatures(arg1:string,arg2:boolean):Promise<void>;

